<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class ApplicationSeeder extends Seeder
{
    public function run()
    {
        DB::table('applications')->insert([
            [
                'job_id' => 1,
                'candidate_id' => 8,
                'assigned_agent_id' => 6,
                'status' => 'pending',
                'remarks' => null,
                'skills' => json_encode(['Laravel', 'PHP', 'MySQL']),
                'full_name' => 'John Doe',
                'date_of_birth' => '1990-05-12',
                'gender' => 'male',
                'nationality' => 'Mauritian',
                'email' => 'john@example.com',
                'phone' => '+23054321000',
                'address' => '123 Palm Street, Port Louis',
                'country' => 'Mauritius',
                'highest_degree' => 'BSc Computer Science',
                'institution' => 'University of Mauritius',
                'field_of_study' => 'Software Engineering',
                'graduation_date' => '2013-12-01',
                'years_experience' => 7,
                'last_employer' => 'Tech Ltd',
                'last_position' => 'Software Developer',
                'employment_duration' => '2016-2022',
                'cover_letter' => 'I am passionate about backend systems...',
                'linkedin' => 'https://linkedin.com/in/johndoe',
                'portfolio' => 'https://johndoe.dev',
                'resume_path' => 'resumes/john_doe_resume.pdf',
                'other_docs_paths' => json_encode(['certificates/john_cert.pdf']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'job_id' => 2,
                'candidate_id' => 7,
                'assigned_agent_id' => 5,
                'status' => 'shortlisted',
                'remarks' => 'Good frontend portfolio',
                'skills' => json_encode(['React', 'HTML', 'CSS']),
                'full_name' => 'Jane Smith',
                'date_of_birth' => '1994-11-03',
                'gender' => 'female',
                'nationality' => 'Mauritian',
                'email' => 'jane@example.com',
                'phone' => '+23058712345',
                'address' => '45 City Road, Curepipe',
                'country' => 'Mauritius',
                'highest_degree' => 'Diploma in Web Design',
                'institution' => 'MITD',
                'field_of_study' => 'Frontend Development',
                'graduation_date' => '2017-08-01',
                'years_experience' => 4,
                'last_employer' => 'Creative Studio',
                'last_position' => 'UI Designer',
                'employment_duration' => '2018-2022',
                'cover_letter' => 'Designing clean and modern UIs is my forte.',
                'linkedin' => null,
                'portfolio' => 'https://janesmith.design',
                'resume_path' => 'resumes/jane_smith_resume.pdf',
                'other_docs_paths' => json_encode([]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'job_id' => 3,
                'candidate_id' => 7,
                'assigned_agent_id' => 5,
                'status' => 'in_review',
                'remarks' => 'Awaiting interview',
                'skills' => json_encode(['Python', 'Pandas', 'Data Visualization']),
                'full_name' => 'Ali Khan',
                'date_of_birth' => '1988-03-22',
                'gender' => 'male',
                'nationality' => 'Pakistani',
                'email' => 'ali.khan@example.com',
                'phone' => '+92 300 4567890',
                'address' => 'Lahore, Punjab, Pakistan',
                'country' => 'Pakistan',
                'highest_degree' => 'Masters in Data Science',
                'institution' => 'Punjab University',
                'field_of_study' => 'Data Analysis',
                'graduation_date' => '2015-05-10',
                'years_experience' => 9,
                'last_employer' => 'DataTech',
                'last_position' => 'Data Analyst',
                'employment_duration' => '2015-2024',
                'cover_letter' => 'I love working with data to solve real-world problems.',
                'linkedin' => 'https://linkedin.com/in/alikhan',
                'portfolio' => null,
                'resume_path' => 'resumes/ali_khan_resume.pdf',
                'other_docs_paths' => json_encode(['certificates/ali_data_cert.pdf']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
